import { ApiConnection } from "platform/connection.js";
import type {
  Channel,
  ChannelBalanceResponse,
  GetInfoResponse,
  WalletBalanceResponse,
} from "./autogenerated-types";
import { joinUrl } from "../common/utils.js";

export type LightningBalance = {
  wallet: WalletBalanceResponse;
  channel: ChannelBalanceResponse;
};

export type LightningDetails = {
  balance: LightningBalance;
  channels: Channel[];
  lightningInfo: GetInfoResponse;
};

export class MiddlewarePages extends ApiConnection {
  constructor(baseUrl: string) {
    super(joinUrl(baseUrl, `v1/pages`));
  }

  async lightning(): Promise<LightningDetails> {
    return await this.get<LightningDetails>("lnd");
  }
}
