import { ApiConnection } from "platform/connection.js";
import type {
  Channel,
  ChannelBalanceResponse,
  GetInfoResponse,
  WalletBalanceResponse,
} from "./autogenerated-types";

type LightningBalance = {
  wallet: WalletBalanceResponse;
  channel: ChannelBalanceResponse;
};
type LightningDetails = {
  balance: LightningBalance;
  channels: Channel[];
  lightningInfo: GetInfoResponse;
};

export class MiddlewarePages extends ApiConnection {
  constructor(baseUrl: string) {
    super(`${baseUrl}${baseUrl.endsWith("/") ? "" : "/"}v1/pages`);
  }

  async lightning(): Promise<LightningDetails> {
    return await this.get<LightningDetails>("lnd");
  }
}
