import {ApiConnection} from 'platform/connection.js';
import type {GetInfoResponse} from '../autogenerated-types';
import {joinUrl} from '../../common/utils.js';

export class LNDInfo extends ApiConnection {
  constructor(baseUrl: string) {
    super(joinUrl(baseUrl, `info`));
  }

  public async generalInfo(): Promise<GetInfoResponse> {
    return await this.get<GetInfoResponse>('');
  }

  public async publicUris(): Promise<string[]> {
    return await this.get<string[]>('/uris');
  }

  public async getStatus(): Promise<{
    operational: boolean;
    unlocked: boolean;
  }> {
    return await this.get<{
      operational: boolean;
      unlocked: boolean;
    }>('/status');
  }

  public async syncStatus(): Promise<{
    percent: string;
    knownBlockCount: number;
    processedBlocks: number;
  }> {
    return await this.get<{
      percent: string;
      knownBlockCount: number;
      processedBlocks: number;
    }>('/sync');
  }

  public async version(): Promise<{version: string; implementation: string}> {
    const data = await this.get<{version: string; implementation?: string}>(
      '/version',
    );
    return {
      implementation: 'lnd',
      ...data,
    };
  }

  public async alias(): Promise<string> {
    return (await this.get<{alias: string}>('/alias')).alias;
  }
}
