import { ApiConnection } from "platform/connection.js";
import type { GetInfoResponse } from "../autogenerated-types";

export class LNDInfo extends ApiConnection {
  constructor(baseUrl: string) {
    super(`${baseUrl}${baseUrl.endsWith("/") ? "" : "/"}info`);
  }

  public async generalInfo(): Promise<GetInfoResponse> {
    return await this.get<GetInfoResponse>("");
  }

  public async publicUris(): Promise<string[]> {
    return await this.get<string[]>("/uris");
  }

  public async getStatus(): Promise<{
    operational: boolean;
    unlocked: boolean;
  }> {
    return await this.get<{
      operational: boolean;
      unlocked: boolean;
    }>("/status");
  }

  public async syncStatus(): Promise<{
    percent: string;
    knownBlockCount: number;
    processedBlocks: number;
  }> {
    return await this.get<{
      percent: string;
      knownBlockCount: number;
      processedBlocks: number;
    }>("/sync");
  }

  public async version(): Promise<string> {
    return (await this.get<{ version: string }>("/version")).version;
  }

  public async alias(): Promise<string> {
    return (await this.get<{ alias: string }>("/alias")).alias;
  }
}
