import { ApiConnection } from "platform/connection.js";
import { joinUrl } from "../../common/utils.js";
import {
  EstimateFeeResponse,
  PendingChannelsResponse,
  ChannelFeeReport,
  Transaction,
} from "../autogenerated-types";
import type { RangeOf2 } from "../../common/types.js";

export type Transaction_extended = Transaction & {
  type:
    | "CHANNEL_OPEN"
    | "CHANNEL_CLOSE"
    | "PENDING_OPEN"
    | "PENDING_CLOSE"
    | "UNKNOWN"
    | "ON_CHAIN_TRANSACTION_SENT"
    | "ON_CHAIN_TRANSACTION_RECEIVED";
};

export type EstimateFeeResponseExtended = EstimateFeeResponse & {
  sweepAmount?: number;
};

export class LNDTransaction extends ApiConnection {
  constructor(baseUrl: string) {
    super(joinUrl(baseUrl, `transaction`));
  }

  // Returns a list of all on chain transactions.
  async getOnChainTransactions(): Promise<Transaction_extended[]> {
    return this.get<Transaction_extended[]>("/");
  }
}
