import { ApiConnection } from "platform/connection.js";
import { ChannelBalanceResponse, WalletBalanceResponse } from "../autogenerated-types";

export class LNDWallet extends ApiConnection {
    constructor(baseUrl: string) {
      super(`${baseUrl}${baseUrl.endsWith("/") ? "" : "/"}wallet`);
    }

    public async onChainBalance(): Promise<WalletBalanceResponse> {
        return await this.get<WalletBalanceResponse>("/btc");
    }

    public async init(seed: string[]): Promise<void> {
        await this.post<{success: boolean}>("/init", { seed });
    }

    public async lightningBalance(): Promise<ChannelBalanceResponse> {
        return await this.get<ChannelBalanceResponse>("/lightning");
    }

    public async generatSeed(): Promise<string[]> {
        return await this.get<string[]>("/seed");
    }
}
