import Citadel from './citadel.js';

export {Manager} from './manager/index.js';
export {Middleware} from './middleware/index.js';
export type {ManagerApps} from './manager/apps';
export type {ManagerAuth, user, changePasswordStatus} from './manager/auth';
export type {ManagerExternal} from './manager/external';
export type {ManagerSystem} from './manager/system';
export type {MiddlewarePages} from './middleware/pages';
export type {MiddlewareLND} from './middleware/lnd';
export type {MiddlewareBitcoin} from './middleware/bitcoin';
export type {LNDChannel} from './middleware/lnd/channel';
export type {LNDInfo} from './middleware/lnd/info';
export type {LNDLightning} from './middleware/lnd/lightning';
export type {LNDTransaction} from './middleware/lnd/transaction';
export type {LNDWallet} from './middleware/lnd/wallet';
export type {RangeOf2} from './common/types.js';

export * from './middleware/autogenerated-types.js';
export * from './middleware/bitcoin-types';
export * from './common/types';

export {
  SyncStatus,
  StatsDump,
  Stats,
  Block,
  BasicBlock,
  Transaction as BitcoinCoreTransaction,
} from './middleware/bitcoin';

export {
  Channel_extended,
  EstimateFeeResponseExtended,
} from './middleware/lnd/channel';

export {extendedPaymentRequest} from './middleware/lnd/lightning';

export {Transaction_extended} from './middleware/lnd/transaction';

export {LightningBalance, LightningDetails} from './middleware/pages';

export {LnAddressSignupResponse} from './manager/external';

export default Citadel;
