import Citadel from "platform/citadel";

export { Manager } from "./manager/index.js";
export { Middleware } from "./middleware/index.js";
export type { ManagerApps } from "./manager/apps";
export type { ManagerAuth, user, changePasswordStatus } from "./manager/auth";
export type { ManagerExternal } from "./manager/external";
export type { ManagerSystem } from "./manager/system";
export type { MiddlewarePages } from "./middleware/pages";
export type { MiddlewareLND } from "./middleware/lnd";
export type { MiddlewareBitcoin } from "./middleware/bitcoin";
export type { LNDChannel } from "./middleware/lnd/channel";
export type { LNDInfo } from "./middleware/lnd/info";
export type { LNDLightning } from "./middleware/lnd/lightning";
export type { LNDWallet } from "./middleware/lnd/wallet";
export * from "./middleware/autogenerated-types";
export type { RangeOf2 } from "./common/types.js";

export default Citadel;
